import Footer from "./components/Footer";
import Hero from "./components/Hero";
import ImagePreview from "./components/ImagePreview";
import ActionButtons from "./components/ActionButtons";

import LoadingSpinner from "./components/LoadingSpinner";
import { useState } from "react";
import Header from "./components/Header";
import UploadBox from "./components/UploadBox";
import CaptionCard from "./components/CaptionCard";
import { generateCaption } from "./api/captionApi";

function App() {
  const [image, setImage] = useState(null);
  const [loading, setLoading] = useState(false);
  const [captions, setCaptions] = useState(null);

  const handleGenerate = async () => {
    if (!image) {
      alert("Please select an image first.");
      return;
    }

    setLoading(true);

    try {
      const data = await generateCaption(image);
      setCaptions(data);
    } catch (error) {
      console.error(error);
      alert("Unable to connect to backend.");
    }

    setLoading(false);
  };
  const resetApp = () => {
  setImage(null);
  setCaptions(null);
};

  return (
    <div className="container">
      <Header />

<Hero />

<UploadBox onImageSelect={setImage} />

{!image && (
  <p
    style={{
      marginTop: "20px",
      color: "#94a3b8",
      textAlign: "center",
    }}
  >
    Supported formats: JPG, JPEG, PNG
  </p>
)}

<ImagePreview image={image} />

<div className="generate-button">
  {loading ? (
    <LoadingSpinner />
  ) : (
    <button onClick={handleGenerate}>
      ✨ Generate AI Caption
    </button>
  )}
</div>

{captions && !captions.ai_enhanced && (
  <div className="warning-box">
    ⚠️ AI enhancement is currently unavailable.
    Showing captions generated by the BLIP model.
  </div>
)}

      {captions && (
  <div className="results">
    <CaptionCard
      title="💼 Professional"
      text={captions.professional}
    />

    <CaptionCard
      title="🎨 Creative"
      text={captions.creative}
    />

    <CaptionCard
      title="📝 Detailed"
      text={captions.detailed}
    />

    <CaptionCard
      title="📱 Social Media"
      text={captions.social}
    />
  </div>
)}
{captions && (
  <ActionButtons
    captions={captions}
    onReset={resetApp}
  />
)}

<Footer />
    </div>
  );
}

export default App;
